#!/bin/bash 

export chimes_revision=be1e8777f83a9a7b08075763b608ffcdadddc987

mkdir chimes-data
cd chimes-data 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/chimes_main_data.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/cross_sections_B87.hdf5 

mkdir SP20_cross_sections
cd SP20_cross_sections
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/redshifts.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z0.000_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z0.200_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z0.400_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z0.600_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z0.800_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z1.000_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z1.200_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z1.400_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z1.600_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z1.800_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z2.000_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z2.200_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z2.400_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z2.600_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z2.800_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z3.000_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z3.200_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z3.400_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z3.600_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z3.800_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z4.000_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z4.200_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z4.400_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z4.600_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z4.800_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z5.000_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z5.200_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z5.400_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z5.600_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z5.800_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z6.000_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z6.200_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z6.400_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z6.600_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z6.800_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z7.000_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z7.200_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z7.400_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z7.600_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z7.800_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z8.000_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z8.200_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z8.400_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z8.600_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z8.800_cross_sections.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/SP20_cross_sections/z9.000_cross_sections.hdf5 

cd .. 
mkdir EqAbundancesTables 
cd EqAbundancesTables 
mkdir colibre_HHe 
cd colibre_HHe 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z0.000_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z0.200_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z0.400_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z0.600_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z0.800_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z1.000_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z1.200_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z1.400_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z1.600_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z1.800_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z2.000_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z2.200_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z2.400_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z2.600_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z2.800_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z3.000_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z3.200_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z3.400_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z3.600_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z3.800_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z4.000_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z4.200_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z4.400_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z4.600_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z4.800_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z5.000_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z5.200_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z5.400_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z5.600_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z5.800_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z6.000_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z6.200_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z6.400_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z6.600_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z6.800_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z7.000_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z7.200_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z7.400_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z7.600_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z7.800_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z8.000_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z8.200_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z8.400_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z8.600_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z8.800_eqm.hdf5 
wget https://bitbucket.org/richings/chimes-data/raw/$chimes_revision/EqAbundancesTables/colibre_HHe/z9.000_eqm.hdf5 
